// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ARM-software/golang-utils/utils/transaction/saga (interfaces: IActionArguments,IActionIdentifier,ITransactionStep,ISagaOrchestrator)
//
// Generated by this command:
//
//	mockgen -destination=./mock_test.go -package=saga github.com/ARM-software/golang-utils/utils/transaction/saga IActionArguments,IActionIdentifier,ITransactionStep,ISagaOrchestrator
//

// Package saga is a generated GoMock package.
package saga

import (
	context "context"
	iter "iter"
	reflect "reflect"

	parallelisation "github.com/ARM-software/golang-utils/utils/parallelisation"
	gomock "go.uber.org/mock/gomock"
)

// MockIActionArguments is a mock of IActionArguments interface.
type MockIActionArguments struct {
	ctrl     *gomock.Controller
	recorder *MockIActionArgumentsMockRecorder
	isgomock struct{}
}

// MockIActionArgumentsMockRecorder is the mock recorder for MockIActionArguments.
type MockIActionArgumentsMockRecorder struct {
	mock *MockIActionArguments
}

// NewMockIActionArguments creates a new mock instance.
func NewMockIActionArguments(ctrl *gomock.Controller) *MockIActionArguments {
	mock := &MockIActionArguments{ctrl: ctrl}
	mock.recorder = &MockIActionArgumentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActionArguments) EXPECT() *MockIActionArgumentsMockRecorder {
	return m.recorder
}

// GetArguments mocks base method.
func (m *MockIActionArguments) GetArguments() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArguments")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetArguments indicates an expected call of GetArguments.
func (mr *MockIActionArgumentsMockRecorder) GetArguments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArguments", reflect.TypeOf((*MockIActionArguments)(nil).GetArguments))
}

// GetIdemKey mocks base method.
func (m *MockIActionArguments) GetIdemKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdemKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdemKey indicates an expected call of GetIdemKey.
func (mr *MockIActionArgumentsMockRecorder) GetIdemKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdemKey", reflect.TypeOf((*MockIActionArguments)(nil).GetIdemKey))
}

// MockIActionIdentifier is a mock of IActionIdentifier interface.
type MockIActionIdentifier struct {
	ctrl     *gomock.Controller
	recorder *MockIActionIdentifierMockRecorder
	isgomock struct{}
}

// MockIActionIdentifierMockRecorder is the mock recorder for MockIActionIdentifier.
type MockIActionIdentifierMockRecorder struct {
	mock *MockIActionIdentifier
}

// NewMockIActionIdentifier creates a new mock instance.
func NewMockIActionIdentifier(ctrl *gomock.Controller) *MockIActionIdentifier {
	mock := &MockIActionIdentifier{ctrl: ctrl}
	mock.recorder = &MockIActionIdentifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActionIdentifier) EXPECT() *MockIActionIdentifierMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockIActionIdentifier) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIActionIdentifierMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIActionIdentifier)(nil).GetName))
}

// GetNamespace mocks base method.
func (m *MockIActionIdentifier) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockIActionIdentifierMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockIActionIdentifier)(nil).GetNamespace))
}

// MockITransactionStep is a mock of ITransactionStep interface.
type MockITransactionStep struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionStepMockRecorder
	isgomock struct{}
}

// MockITransactionStepMockRecorder is the mock recorder for MockITransactionStep.
type MockITransactionStepMockRecorder struct {
	mock *MockITransactionStep
}

// NewMockITransactionStep creates a new mock instance.
func NewMockITransactionStep(ctrl *gomock.Controller) *MockITransactionStep {
	mock := &MockITransactionStep{ctrl: ctrl}
	mock.recorder = &MockITransactionStepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionStep) EXPECT() *MockITransactionStepMockRecorder {
	return m.recorder
}

// Compensate mocks base method.
func (m *MockITransactionStep) Compensate(ctx context.Context, args IActionArguments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compensate", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compensate indicates an expected call of Compensate.
func (mr *MockITransactionStepMockRecorder) Compensate(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compensate", reflect.TypeOf((*MockITransactionStep)(nil).Compensate), ctx, args)
}

// Execute mocks base method.
func (m *MockITransactionStep) Execute(ctx context.Context, args IActionArguments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockITransactionStepMockRecorder) Execute(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockITransactionStep)(nil).Execute), ctx, args)
}

// GetID mocks base method.
func (m *MockITransactionStep) GetID() IActionIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(IActionIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockITransactionStepMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockITransactionStep)(nil).GetID))
}

// MockISagaOrchestrator is a mock of ISagaOrchestrator interface.
type MockISagaOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockISagaOrchestratorMockRecorder
	isgomock struct{}
}

// MockISagaOrchestratorMockRecorder is the mock recorder for MockISagaOrchestrator.
type MockISagaOrchestratorMockRecorder struct {
	mock *MockISagaOrchestrator
}

// NewMockISagaOrchestrator creates a new mock instance.
func NewMockISagaOrchestrator(ctrl *gomock.Controller) *MockISagaOrchestrator {
	mock := &MockISagaOrchestrator{ctrl: ctrl}
	mock.recorder = &MockISagaOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISagaOrchestrator) EXPECT() *MockISagaOrchestratorMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockISagaOrchestrator) Clone() parallelisation.IExecutionGroup[ITransactionStep] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone")
	ret0, _ := ret[0].(parallelisation.IExecutionGroup[ITransactionStep])
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockISagaOrchestratorMockRecorder) Clone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockISagaOrchestrator)(nil).Clone))
}

// CopyFunctions mocks base method.
func (m *MockISagaOrchestrator) CopyFunctions(g parallelisation.IExecutionGroup[ITransactionStep]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CopyFunctions", g)
}

// CopyFunctions indicates an expected call of CopyFunctions.
func (mr *MockISagaOrchestratorMockRecorder) CopyFunctions(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFunctions", reflect.TypeOf((*MockISagaOrchestrator)(nil).CopyFunctions), g)
}

// Execute mocks base method.
func (m *MockISagaOrchestrator) Execute(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockISagaOrchestratorMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockISagaOrchestrator)(nil).Execute), ctx)
}

// Len mocks base method.
func (m *MockISagaOrchestrator) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockISagaOrchestratorMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockISagaOrchestrator)(nil).Len))
}

// RegisterFunction mocks base method.
func (m *MockISagaOrchestrator) RegisterFunction(function ...ITransactionStep) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range function {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RegisterFunction", varargs...)
}

// RegisterFunction indicates an expected call of RegisterFunction.
func (mr *MockISagaOrchestratorMockRecorder) RegisterFunction(function ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFunction", reflect.TypeOf((*MockISagaOrchestrator)(nil).RegisterFunction), function...)
}

// RegisterFunctions mocks base method.
func (m *MockISagaOrchestrator) RegisterFunctions(function iter.Seq[ITransactionStep]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterFunctions", function)
}

// RegisterFunctions indicates an expected call of RegisterFunctions.
func (mr *MockISagaOrchestratorMockRecorder) RegisterFunctions(function any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFunctions", reflect.TypeOf((*MockISagaOrchestrator)(nil).RegisterFunctions), function)
}
