run:
  timeout: 5m

  # Run linters over integration tests
  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - goimports
    # - gci FIXME uncomment when https://github.com/golangci/golangci-lint/issues/2985 is fixed

# Auto-fix any found issues
issues:
  fix: true

linters-settings:
  goimports:
    local-prefixes: github.com/ARM-software
  gci:
    local-prefixes: github.com/ARM-software
