version: "2"
run:
  build-tags:
    - integration
linters:
  default: none
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/ARM-software)
    goimports:
      local-prefixes:
        - github.com/ARM-software
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
