run:
  timeout: 10m

  # Run linters over integration tests
  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - stylecheck
    - gosec
    - goimports
    - gci
    - revive
    - gocritic
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/ARM-software
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/ARM-software)
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"
