run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - goimports
    - gci

# Auto-fix any found issues
issues:
  fix: true

linters-settings:
  goimports:
    local-prefixes: github.com/ARMmbed
  gci:
    local-prefixes: github.com/ARMmbed
