run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - goimports
    - gci

linters-settings:
  goimports:
    local-prefixes: github.com/ARMmbed
  gci:
    local-prefixes: github.com/ARMmbed
