run:
  timeout: 10m

  # Run linters over integration tests
  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - stylecheck
    - gosec
    - goimports
    - gci
    - revive
    - gocritic
    - unconvert
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/ARM-software
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/ARM-software)
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"
  misspell:
    locale: UK
    extra-words:
      - typo: "sanetisation"
        correction: "sanitisation"
      - typo: "sanetise"
        correction: "sanitise"
      - typo: "sanetising"
        correction: "sanitising"
