#
# Copyright (C) 2021-2022 Arm. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
[ProjectConfig]
# Only path variables can and must contain 'DIR', 'PATH' or 'ROOT' in their name as
# these tokens are used to identify path variables from other variable types.
MASTER_BRANCH = "master"
PROJECT_NAME = "Golang Utilities"
PACKAGE_NAME = "golang-utils"
PROJECT_UUID = '5e7ed86f-7c3b-4d78-96f8-2b92106f1f86'
PROJECT_ROOT = "."
NEWS_DIR = "changes/"
SOURCE_DIR = "utils"
RELEASE_BRANCH_PATTERN = "^release.*$"
MODULE_TO_DOCUMENT = "golang-utils"
DOCUMENTATION_DEFAULT_OUTPUT_PATH = "local_docs"
DOCUMENTATION_PRODUCTION_OUTPUT_PATH = "docs"
VERSION_FILE_PATH = "utils/module.properties"
CHANGELOG_FILE_PATH = "CHANGELOG.md"
AWS_BUCKET=""
PROGRAMMING_LANGUAGE = "Golang"



[AutoVersionConfig]
CONFIG_NAME = "JAVA"
PRERELEASE_TOKEN = "beta"
BUILD_TOKEN = "dev"
TAG_TEMPLATE = "release/{version}"
targets = [ "utils/module.properties",]

[AutoVersionConfig.key_aliases]
Version = "VERSION_KEY"
MajorVersion = "major"
MinorVersion = "minor"
PatchVersion = "patch"
CommitHash = "COMMIT"

[AutoVersionConfig.trigger_patterns]
major = "news/*.major"
minor = "news/*.feature"
patch = "news/*.bugfix"

[tool.towncrier]
directory = "news"
filename = "CHANGELOG.md"
package = "continuous_delivery_scripts"
title_format = "{version} ({project_date})"
start_string = """
[//]: # (begin_release_notes)
"""

[[tool.towncrier.type]]
directory = "major"
name = "Major changes"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = false

[tool.black]
line-length = 120

[spdx]
CreatorWebsite = "spdx.org"
PathToSpdx = "spdx/spdxdocs"
UUID="d9e2187c-30b4-11eb-adc1-0242ac120002"
