// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./interfaces.go -destination=../../mocks/mock_annotations.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	annotations "github.com/ARM-software/golang-utils/utils/logs/annotations"
	gomock "go.uber.org/mock/gomock"
)

// MockIAnnotationLogger is a mock of IAnnotationLogger interface.
type MockIAnnotationLogger struct {
	ctrl     *gomock.Controller
	recorder *MockIAnnotationLoggerMockRecorder
	isgomock struct{}
}

// MockIAnnotationLoggerMockRecorder is the mock recorder for MockIAnnotationLogger.
type MockIAnnotationLoggerMockRecorder struct {
	mock *MockIAnnotationLogger
}

// NewMockIAnnotationLogger creates a new mock instance.
func NewMockIAnnotationLogger(ctrl *gomock.Controller) *MockIAnnotationLogger {
	mock := &MockIAnnotationLogger{ctrl: ctrl}
	mock.recorder = &MockIAnnotationLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnnotationLogger) EXPECT() *MockIAnnotationLoggerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockIAnnotationLogger) Check() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockIAnnotationLoggerMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockIAnnotationLogger)(nil).Check))
}

// Close mocks base method.
func (m *MockIAnnotationLogger) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIAnnotationLoggerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIAnnotationLogger)(nil).Close))
}

// Log mocks base method.
func (m *MockIAnnotationLogger) Log(output ...any) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range output {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockIAnnotationLoggerMockRecorder) Log(output ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockIAnnotationLogger)(nil).Log), output...)
}

// LogError mocks base method.
func (m *MockIAnnotationLogger) LogError(err ...any) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range err {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogError", varargs...)
}

// LogError indicates an expected call of LogError.
func (mr *MockIAnnotationLoggerMockRecorder) LogError(err ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockIAnnotationLogger)(nil).LogError), err...)
}

// SetLogSource mocks base method.
func (m *MockIAnnotationLogger) SetLogSource(source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogSource", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLogSource indicates an expected call of SetLogSource.
func (mr *MockIAnnotationLoggerMockRecorder) SetLogSource(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogSource", reflect.TypeOf((*MockIAnnotationLogger)(nil).SetLogSource), source)
}

// SetLoggerSource mocks base method.
func (m *MockIAnnotationLogger) SetLoggerSource(source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoggerSource", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLoggerSource indicates an expected call of SetLoggerSource.
func (mr *MockIAnnotationLoggerMockRecorder) SetLoggerSource(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoggerSource", reflect.TypeOf((*MockIAnnotationLogger)(nil).SetLoggerSource), source)
}

// WriteAnnotation mocks base method.
func (m *MockIAnnotationLogger) WriteAnnotation(annotation *annotations.Annotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAnnotation", annotation)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAnnotation indicates an expected call of WriteAnnotation.
func (mr *MockIAnnotationLoggerMockRecorder) WriteAnnotation(annotation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAnnotation", reflect.TypeOf((*MockIAnnotationLogger)(nil).WriteAnnotation), annotation)
}

// WriteError mocks base method.
func (m *MockIAnnotationLogger) WriteError(message string, options ...annotations.AnnotationOption) error {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteError", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteError indicates an expected call of WriteError.
func (mr *MockIAnnotationLoggerMockRecorder) WriteError(message any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteError", reflect.TypeOf((*MockIAnnotationLogger)(nil).WriteError), varargs...)
}

// WriteNotice mocks base method.
func (m *MockIAnnotationLogger) WriteNotice(message string, options ...annotations.AnnotationOption) error {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteNotice", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteNotice indicates an expected call of WriteNotice.
func (mr *MockIAnnotationLoggerMockRecorder) WriteNotice(message any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteNotice", reflect.TypeOf((*MockIAnnotationLogger)(nil).WriteNotice), varargs...)
}

// WriteWarning mocks base method.
func (m *MockIAnnotationLogger) WriteWarning(message string, options ...annotations.AnnotationOption) error {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteWarning", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteWarning indicates an expected call of WriteWarning.
func (mr *MockIAnnotationLoggerMockRecorder) WriteWarning(message any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteWarning", reflect.TypeOf((*MockIAnnotationLogger)(nil).WriteWarning), varargs...)
}

// MockIFormatter is a mock of IFormatter interface.
type MockIFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockIFormatterMockRecorder
	isgomock struct{}
}

// MockIFormatterMockRecorder is the mock recorder for MockIFormatter.
type MockIFormatterMockRecorder struct {
	mock *MockIFormatter
}

// NewMockIFormatter creates a new mock instance.
func NewMockIFormatter(ctrl *gomock.Controller) *MockIFormatter {
	mock := &MockIFormatter{ctrl: ctrl}
	mock.recorder = &MockIFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFormatter) EXPECT() *MockIFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method.
func (m *MockIFormatter) Format(annotation *annotations.Annotation) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", annotation)
	ret0, _ := ret[0].(string)
	return ret0
}

// Format indicates an expected call of Format.
func (mr *MockIFormatterMockRecorder) Format(annotation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockIFormatter)(nil).Format), annotation)
}
