// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ARM-software/golang-utils/utils/validation/jsonschema (interfaces: ISchemaValidator)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_jsonschema.go -package=mocks github.com/ARM-software/golang-utils/utils/validation/jsonschema ISchemaValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	filesystem "github.com/ARM-software/golang-utils/utils/filesystem"
	gomock "go.uber.org/mock/gomock"
)

// MockISchemaValidator is a mock of ISchemaValidator interface.
type MockISchemaValidator struct {
	ctrl     *gomock.Controller
	recorder *MockISchemaValidatorMockRecorder
	isgomock struct{}
}

// MockISchemaValidatorMockRecorder is the mock recorder for MockISchemaValidator.
type MockISchemaValidatorMockRecorder struct {
	mock *MockISchemaValidator
}

// NewMockISchemaValidator creates a new mock instance.
func NewMockISchemaValidator(ctrl *gomock.Controller) *MockISchemaValidator {
	mock := &MockISchemaValidator{ctrl: ctrl}
	mock.recorder = &MockISchemaValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISchemaValidator) EXPECT() *MockISchemaValidatorMockRecorder {
	return m.recorder
}

// ValidateContent mocks base method.
func (m *MockISchemaValidator) ValidateContent(arg0 context.Context, arg1 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateContent indicates an expected call of ValidateContent.
func (mr *MockISchemaValidatorMockRecorder) ValidateContent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContent", reflect.TypeOf((*MockISchemaValidator)(nil).ValidateContent), arg0, arg1)
}

// ValidateFile mocks base method.
func (m *MockISchemaValidator) ValidateFile(ctx context.Context, filepath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateFile", ctx, filepath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateFile indicates an expected call of ValidateFile.
func (mr *MockISchemaValidatorMockRecorder) ValidateFile(ctx, filepath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateFile", reflect.TypeOf((*MockISchemaValidator)(nil).ValidateFile), ctx, filepath)
}

// ValidateFileInFS mocks base method.
func (m *MockISchemaValidator) ValidateFileInFS(ctx context.Context, fs filesystem.FS, filepath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateFileInFS", ctx, fs, filepath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateFileInFS indicates an expected call of ValidateFileInFS.
func (mr *MockISchemaValidatorMockRecorder) ValidateFileInFS(ctx, fs, filepath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateFileInFS", reflect.TypeOf((*MockISchemaValidator)(nil).ValidateFileInFS), ctx, fs, filepath)
}
