// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ARM-software/golang-utils/utils/collection/stack (interfaces: IStack)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_stack.go -package=mocks github.com/ARM-software/golang-utils/utils/collection/stack IStack
//

// Package mocks is a generated GoMock package.
package mocks

import (
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIStack is a mock of IStack interface.
type MockIStack[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockIStackMockRecorder[T]
	isgomock struct{}
}

// MockIStackMockRecorder is the mock recorder for MockIStack.
type MockIStackMockRecorder[T any] struct {
	mock *MockIStack[T]
}

// NewMockIStack creates a new mock instance.
func NewMockIStack[T any](ctrl *gomock.Controller) *MockIStack[T] {
	mock := &MockIStack[T]{ctrl: ctrl}
	mock.recorder = &MockIStackMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStack[T]) EXPECT() *MockIStackMockRecorder[T] {
	return m.recorder
}

// Clear mocks base method.
func (m *MockIStack[T]) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockIStackMockRecorder[T]) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockIStack[T])(nil).Clear))
}

// IsEmpty mocks base method.
func (m *MockIStack[T]) IsEmpty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockIStackMockRecorder[T]) IsEmpty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockIStack[T])(nil).IsEmpty))
}

// Len mocks base method.
func (m *MockIStack[T]) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockIStackMockRecorder[T]) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockIStack[T])(nil).Len))
}

// Peek mocks base method.
func (m *MockIStack[T]) Peek() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek")
	ret0, _ := ret[0].(T)
	return ret0
}

// Peek indicates an expected call of Peek.
func (mr *MockIStackMockRecorder[T]) Peek() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockIStack[T])(nil).Peek))
}

// Pop mocks base method.
func (m *MockIStack[T]) Pop() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pop")
	ret0, _ := ret[0].(T)
	return ret0
}

// Pop indicates an expected call of Pop.
func (mr *MockIStackMockRecorder[T]) Pop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockIStack[T])(nil).Pop))
}

// Push mocks base method.
func (m *MockIStack[T]) Push(value ...T) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range value {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Push", varargs...)
}

// Push indicates an expected call of Push.
func (mr *MockIStackMockRecorder[T]) Push(value ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockIStack[T])(nil).Push), value...)
}

// PushSequence mocks base method.
func (m *MockIStack[T]) PushSequence(seq iter.Seq[T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushSequence", seq)
}

// PushSequence indicates an expected call of PushSequence.
func (mr *MockIStackMockRecorder[T]) PushSequence(seq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushSequence", reflect.TypeOf((*MockIStack[T])(nil).PushSequence), seq)
}

// Values mocks base method.
func (m *MockIStack[T]) Values() iter.Seq[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Values")
	ret0, _ := ret[0].(iter.Seq[T])
	return ret0
}

// Values indicates an expected call of Values.
func (mr *MockIStackMockRecorder[T]) Values() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Values", reflect.TypeOf((*MockIStack[T])(nil).Values))
}
