// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\adrcab01\Repos\golang-utils\utils\logs\summary\interfaces.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\adrcab01\Repos\golang-utils\utils\logs\summary\interfaces.go -destination=C:\Users\adrcab01\Repos\golang-utils\utils\mocks\mock_summary.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISummaryLogger is a mock of ISummaryLogger interface.
type MockISummaryLogger struct {
	ctrl     *gomock.Controller
	recorder *MockISummaryLoggerMockRecorder
	isgomock struct{}
}

// MockISummaryLoggerMockRecorder is the mock recorder for MockISummaryLogger.
type MockISummaryLoggerMockRecorder struct {
	mock *MockISummaryLogger
}

// NewMockISummaryLogger creates a new mock instance.
func NewMockISummaryLogger(ctrl *gomock.Controller) *MockISummaryLogger {
	mock := &MockISummaryLogger{ctrl: ctrl}
	mock.recorder = &MockISummaryLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISummaryLogger) EXPECT() *MockISummaryLoggerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockISummaryLogger) Check() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockISummaryLoggerMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockISummaryLogger)(nil).Check))
}

// Close mocks base method.
func (m *MockISummaryLogger) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockISummaryLoggerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockISummaryLogger)(nil).Close))
}

// Log mocks base method.
func (m *MockISummaryLogger) Log(output ...any) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range output {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockISummaryLoggerMockRecorder) Log(output ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockISummaryLogger)(nil).Log), output...)
}

// LogError mocks base method.
func (m *MockISummaryLogger) LogError(err ...any) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range err {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogError", varargs...)
}

// LogError indicates an expected call of LogError.
func (mr *MockISummaryLoggerMockRecorder) LogError(err ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockISummaryLogger)(nil).LogError), err...)
}

// SetLogSource mocks base method.
func (m *MockISummaryLogger) SetLogSource(source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogSource", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLogSource indicates an expected call of SetLogSource.
func (mr *MockISummaryLoggerMockRecorder) SetLogSource(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogSource", reflect.TypeOf((*MockISummaryLogger)(nil).SetLogSource), source)
}

// SetLoggerSource mocks base method.
func (m *MockISummaryLogger) SetLoggerSource(source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoggerSource", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLoggerSource indicates an expected call of SetLoggerSource.
func (mr *MockISummaryLoggerMockRecorder) SetLoggerSource(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoggerSource", reflect.TypeOf((*MockISummaryLogger)(nil).SetLoggerSource), source)
}

// WriteString mocks base method.
func (m *MockISummaryLogger) WriteString(content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteString", content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteString indicates an expected call of WriteString.
func (mr *MockISummaryLoggerMockRecorder) WriteString(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteString", reflect.TypeOf((*MockISummaryLogger)(nil).WriteString), content)
}

// WriteStringF mocks base method.
func (m *MockISummaryLogger) WriteStringF(format string, values ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteStringF", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteStringF indicates an expected call of WriteStringF.
func (mr *MockISummaryLoggerMockRecorder) WriteStringF(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStringF", reflect.TypeOf((*MockISummaryLogger)(nil).WriteStringF), varargs...)
}
