// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ARM-software/golang-utils/utils/pipeline (interfaces: IStep,ISimplePipeline,IPipeline)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_pipeline.go -package=mocks github.com/ARM-software/golang-utils/utils/pipeline IStep,ISimplePipeline,IPipeline
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	parallelisation "github.com/ARM-software/golang-utils/utils/parallelisation"
	pipeline "github.com/ARM-software/golang-utils/utils/pipeline"
	gomock "go.uber.org/mock/gomock"
)

// MockIStep is a mock of IStep interface.
type MockIStep[I any, O any] struct {
	ctrl     *gomock.Controller
	recorder *MockIStepMockRecorder[I, O]
	isgomock struct{}
}

// MockIStepMockRecorder is the mock recorder for MockIStep.
type MockIStepMockRecorder[I any, O any] struct {
	mock *MockIStep[I, O]
}

// NewMockIStep creates a new mock instance.
func NewMockIStep[I any, O any](ctrl *gomock.Controller) *MockIStep[I, O] {
	mock := &MockIStep[I, O]{ctrl: ctrl}
	mock.recorder = &MockIStepMockRecorder[I, O]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStep[I, O]) EXPECT() *MockIStepMockRecorder[I, O] {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIStep[I, O]) Execute(arg0 context.Context, arg1 I) (O, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(O)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockIStepMockRecorder[I, O]) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIStep[I, O])(nil).Execute), arg0, arg1)
}

// GetName mocks base method.
func (m *MockIStep[I, O]) GetName() *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(*string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIStepMockRecorder[I, O]) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIStep[I, O])(nil).GetName))
}

// GetOptions mocks base method.
func (m *MockIStep[I, O]) GetOptions() *pipeline.StepOptions[I, O] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions")
	ret0, _ := ret[0].(*pipeline.StepOptions[I, O])
	return ret0
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockIStepMockRecorder[I, O]) GetOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockIStep[I, O])(nil).GetOptions))
}

// MockISimplePipeline is a mock of ISimplePipeline interface.
type MockISimplePipeline[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockISimplePipelineMockRecorder[T]
	isgomock struct{}
}

// MockISimplePipelineMockRecorder is the mock recorder for MockISimplePipeline.
type MockISimplePipelineMockRecorder[T any] struct {
	mock *MockISimplePipeline[T]
}

// NewMockISimplePipeline creates a new mock instance.
func NewMockISimplePipeline[T any](ctrl *gomock.Controller) *MockISimplePipeline[T] {
	mock := &MockISimplePipeline[T]{ctrl: ctrl}
	mock.recorder = &MockISimplePipelineMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISimplePipeline[T]) EXPECT() *MockISimplePipelineMockRecorder[T] {
	return m.recorder
}

// Execute mocks base method.
func (m *MockISimplePipeline[T]) Execute(arg0 context.Context, arg1 T) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockISimplePipelineMockRecorder[T]) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockISimplePipeline[T])(nil).Execute), arg0, arg1)
}

// RegisterStep mocks base method.
func (m *MockISimplePipeline[T]) RegisterStep(arg0 ...pipeline.IStep[T, T]) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RegisterStep", varargs...)
}

// RegisterStep indicates an expected call of RegisterStep.
func (mr *MockISimplePipelineMockRecorder[T]) RegisterStep(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterStep", reflect.TypeOf((*MockISimplePipeline[T])(nil).RegisterStep), arg0...)
}

// RegisterTransform mocks base method.
func (m *MockISimplePipeline[T]) RegisterTransform(name string, transform pipeline.TransformFunc[T, T], options ...pipeline.Option[T]) {
	m.ctrl.T.Helper()
	varargs := []any{name, transform}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RegisterTransform", varargs...)
}

// RegisterTransform indicates an expected call of RegisterTransform.
func (mr *MockISimplePipelineMockRecorder[T]) RegisterTransform(name, transform any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, transform}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTransform", reflect.TypeOf((*MockISimplePipeline[T])(nil).RegisterTransform), varargs...)
}

// RegisterTransformGroup mocks base method.
func (m *MockISimplePipeline[T]) RegisterTransformGroup(name *string, group *parallelisation.TransformGroup[T, T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterTransformGroup", name, group)
}

// RegisterTransformGroup indicates an expected call of RegisterTransformGroup.
func (mr *MockISimplePipelineMockRecorder[T]) RegisterTransformGroup(name, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTransformGroup", reflect.TypeOf((*MockISimplePipeline[T])(nil).RegisterTransformGroup), name, group)
}

// MockIPipeline is a mock of IPipeline interface.
type MockIPipeline[I any, O any] struct {
	ctrl     *gomock.Controller
	recorder *MockIPipelineMockRecorder[I, O]
	isgomock struct{}
}

// MockIPipelineMockRecorder is the mock recorder for MockIPipeline.
type MockIPipelineMockRecorder[I any, O any] struct {
	mock *MockIPipeline[I, O]
}

// NewMockIPipeline creates a new mock instance.
func NewMockIPipeline[I any, O any](ctrl *gomock.Controller) *MockIPipeline[I, O] {
	mock := &MockIPipeline[I, O]{ctrl: ctrl}
	mock.recorder = &MockIPipelineMockRecorder[I, O]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPipeline[I, O]) EXPECT() *MockIPipelineMockRecorder[I, O] {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIPipeline[I, O]) Execute(arg0 context.Context, arg1 I) (O, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(O)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIPipelineMockRecorder[I, O]) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIPipeline[I, O])(nil).Execute), arg0, arg1)
}
