// Code generated by "enumer -type=PairSplitMode -text -json -yaml"; DO NOT EDIT.

package collection

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PairSplitModeName = "SplitAllMatchSplitFirstMatch"

var _PairSplitModeIndex = [...]uint8{0, 13, 28}

const _PairSplitModeLowerName = "splitallmatchsplitfirstmatch"

func (i PairSplitMode) String() string {
	if i < 0 || i >= PairSplitMode(len(_PairSplitModeIndex)-1) {
		return fmt.Sprintf("PairSplitMode(%d)", i)
	}
	return _PairSplitModeName[_PairSplitModeIndex[i]:_PairSplitModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PairSplitModeNoOp() {
	var x [1]struct{}
	_ = x[SplitAllMatch-(0)]
	_ = x[SplitFirstMatch-(1)]
}

var _PairSplitModeValues = []PairSplitMode{SplitAllMatch, SplitFirstMatch}

var _PairSplitModeNameToValueMap = map[string]PairSplitMode{
	_PairSplitModeName[0:13]:       SplitAllMatch,
	_PairSplitModeLowerName[0:13]:  SplitAllMatch,
	_PairSplitModeName[13:28]:      SplitFirstMatch,
	_PairSplitModeLowerName[13:28]: SplitFirstMatch,
}

var _PairSplitModeNames = []string{
	_PairSplitModeName[0:13],
	_PairSplitModeName[13:28],
}

// PairSplitModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PairSplitModeString(s string) (PairSplitMode, error) {
	if val, ok := _PairSplitModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PairSplitModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PairSplitMode values", s)
}

// PairSplitModeValues returns all values of the enum
func PairSplitModeValues() []PairSplitMode {
	return _PairSplitModeValues
}

// PairSplitModeStrings returns a slice of all String values of the enum
func PairSplitModeStrings() []string {
	strs := make([]string, len(_PairSplitModeNames))
	copy(strs, _PairSplitModeNames)
	return strs
}

// IsAPairSplitMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PairSplitMode) IsAPairSplitMode() bool {
	for _, v := range _PairSplitModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PairSplitMode
func (i PairSplitMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PairSplitMode
func (i *PairSplitMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PairSplitMode should be a string, got %s", data)
	}

	var err error
	*i, err = PairSplitModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PairSplitMode
func (i PairSplitMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PairSplitMode
func (i *PairSplitMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = PairSplitModeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for PairSplitMode
func (i PairSplitMode) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for PairSplitMode
func (i *PairSplitMode) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = PairSplitModeString(s)
	return err
}
