version: 2.1

executors:
  go:
    docker:
      - image: golang:1.15.7
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

  golangci-lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

jobs:
  # Run go formatting, linting and static analysis checks
  lint-go:
    executor:
      name: golangci-lint
    parameters:
      working_directory:
        description: "Which directory to run tests in"
        type: string
    steps:
      - checkout
      - run:
          name: Run go formatting, linting and static analysis checks
          working_directory: <<parameters.working_directory>>
          command: |
            golangci-lint run -v

  testing:
    executor:
      name: go
    parameters:
      directory:
        description: "Where to run the tests"
        type: string
    steps:
      - checkout
      - run:
          working_directory: <<parameters.directory>>
          command: go test -cover ./...

workflows:
  deploy:
    jobs:
      - lint-go:
          name: lint-utils
          working_directory: utils
          filters:
            branches:
              ignore:
                - master

      - testing:
          name: test-utils
          directory: utils
