// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ARM-software/golang-utils/utils/parallelisation/warden (interfaces: IState)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_warden.go -package=mocks github.com/ARM-software/golang-utils/utils/parallelisation/warden IState
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIState is a mock of IState interface.
type MockIState struct {
	ctrl     *gomock.Controller
	recorder *MockIStateMockRecorder
	isgomock struct{}
}

// MockIStateMockRecorder is the mock recorder for MockIState.
type MockIStateMockRecorder struct {
	mock *MockIState
}

// NewMockIState creates a new mock instance.
func NewMockIState(ctrl *gomock.Controller) *MockIState {
	mock := &MockIState{ctrl: ctrl}
	mock.recorder = &MockIStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIState) EXPECT() *MockIStateMockRecorder {
	return m.recorder
}

// Alive mocks base method.
func (m *MockIState) Alive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Alive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Alive indicates an expected call of Alive.
func (mr *MockIStateMockRecorder) Alive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Alive", reflect.TypeOf((*MockIState)(nil).Alive))
}

// Context mocks base method.
func (m *MockIState) Context(parent context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", parent)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockIStateMockRecorder) Context(parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockIState)(nil).Context), parent)
}

// Dead mocks base method.
func (m *MockIState) Dead() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dead")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Dead indicates an expected call of Dead.
func (mr *MockIStateMockRecorder) Dead() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dead", reflect.TypeOf((*MockIState)(nil).Dead))
}

// Dying mocks base method.
func (m *MockIState) Dying() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dying")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Dying indicates an expected call of Dying.
func (mr *MockIStateMockRecorder) Dying() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dying", reflect.TypeOf((*MockIState)(nil).Dying))
}

// Err mocks base method.
func (m *MockIState) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockIStateMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockIState)(nil).Err))
}

// Go mocks base method.
func (m *MockIState) Go(f func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Go", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Go indicates an expected call of Go.
func (mr *MockIStateMockRecorder) Go(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Go", reflect.TypeOf((*MockIState)(nil).Go), f)
}

// Kill mocks base method.
func (m *MockIState) Kill(arg0 error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kill", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Kill indicates an expected call of Kill.
func (mr *MockIStateMockRecorder) Kill(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MockIState)(nil).Kill), arg0)
}

// Wait mocks base method.
func (m *MockIState) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockIStateMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockIState)(nil).Wait))
}
