// Code generated by "enumer -type=Severity -text -json -yaml"; DO NOT EDIT.

package annotations

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SeverityName = "SeverityErrorSeverityWarningSeverityNotice"

var _SeverityIndex = [...]uint8{0, 13, 28, 42}

const _SeverityLowerName = "severityerrorseveritywarningseveritynotice"

func (i Severity) String() string {
	if i < 0 || i >= Severity(len(_SeverityIndex)-1) {
		return fmt.Sprintf("Severity(%d)", i)
	}
	return _SeverityName[_SeverityIndex[i]:_SeverityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SeverityNoOp() {
	var x [1]struct{}
	_ = x[SeverityError-(0)]
	_ = x[SeverityWarning-(1)]
	_ = x[SeverityNotice-(2)]
}

var _SeverityValues = []Severity{SeverityError, SeverityWarning, SeverityNotice}

var _SeverityNameToValueMap = map[string]Severity{
	_SeverityName[0:13]:       SeverityError,
	_SeverityLowerName[0:13]:  SeverityError,
	_SeverityName[13:28]:      SeverityWarning,
	_SeverityLowerName[13:28]: SeverityWarning,
	_SeverityName[28:42]:      SeverityNotice,
	_SeverityLowerName[28:42]: SeverityNotice,
}

var _SeverityNames = []string{
	_SeverityName[0:13],
	_SeverityName[13:28],
	_SeverityName[28:42],
}

// SeverityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SeverityString(s string) (Severity, error) {
	if val, ok := _SeverityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SeverityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Severity values", s)
}

// SeverityValues returns all values of the enum
func SeverityValues() []Severity {
	return _SeverityValues
}

// SeverityStrings returns a slice of all String values of the enum
func SeverityStrings() []string {
	strs := make([]string, len(_SeverityNames))
	copy(strs, _SeverityNames)
	return strs
}

// IsASeverity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Severity) IsASeverity() bool {
	for _, v := range _SeverityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Severity
func (i Severity) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Severity
func (i *Severity) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Severity should be a string, got %s", data)
	}

	var err error
	*i, err = SeverityString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Severity
func (i Severity) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Severity
func (i *Severity) UnmarshalText(text []byte) error {
	var err error
	*i, err = SeverityString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Severity
func (i Severity) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Severity
func (i *Severity) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = SeverityString(s)
	return err
}
