// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easyjson

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson(in *jlexer.Lexer, out *TestingStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Int = int(in.Int())
			}
		case "Int8":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Int8 = int8(in.Int8())
			}
		case "Int16":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Int16 = int16(in.Int16())
			}
		case "Int32":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Int32 = int32(in.Int32())
			}
		case "Int64":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Int64 = int64(in.Int64())
			}
		case "String":
			if in.IsNull() {
				in.Skip()
			} else {
				out.String = string(in.String())
			}
		case "Bool":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bool = bool(in.Bool())
			}
		case "Duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = time.Duration(in.Int64())
			}
		case "SString":
			if in.IsNull() {
				in.Skip()
				out.SString = nil
			} else {
				in.Delim('[')
				if out.SString == nil {
					if !in.IsDelim(']') {
						out.SString = make([]string, 0, 4)
					} else {
						out.SString = []string{}
					}
				} else {
					out.SString = (out.SString)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.SString = append(out.SString, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SInt":
			if in.IsNull() {
				in.Skip()
				out.SInt = nil
			} else {
				in.Delim('[')
				if out.SInt == nil {
					if !in.IsDelim(']') {
						out.SInt = make([]int, 0, 8)
					} else {
						out.SInt = []int{}
					}
				} else {
					out.SInt = (out.SInt)[:0]
				}
				for !in.IsDelim(']') {
					var v2 int
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = int(in.Int())
					}
					out.SInt = append(out.SInt, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SInt8":
			if in.IsNull() {
				in.Skip()
				out.SInt8 = nil
			} else {
				in.Delim('[')
				if out.SInt8 == nil {
					if !in.IsDelim(']') {
						out.SInt8 = make([]int8, 0, 64)
					} else {
						out.SInt8 = []int8{}
					}
				} else {
					out.SInt8 = (out.SInt8)[:0]
				}
				for !in.IsDelim(']') {
					var v3 int8
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = int8(in.Int8())
					}
					out.SInt8 = append(out.SInt8, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SInt16":
			if in.IsNull() {
				in.Skip()
				out.SInt16 = nil
			} else {
				in.Delim('[')
				if out.SInt16 == nil {
					if !in.IsDelim(']') {
						out.SInt16 = make([]int16, 0, 32)
					} else {
						out.SInt16 = []int16{}
					}
				} else {
					out.SInt16 = (out.SInt16)[:0]
				}
				for !in.IsDelim(']') {
					var v4 int16
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = int16(in.Int16())
					}
					out.SInt16 = append(out.SInt16, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SInt32":
			if in.IsNull() {
				in.Skip()
				out.SInt32 = nil
			} else {
				in.Delim('[')
				if out.SInt32 == nil {
					if !in.IsDelim(']') {
						out.SInt32 = make([]int32, 0, 16)
					} else {
						out.SInt32 = []int32{}
					}
				} else {
					out.SInt32 = (out.SInt32)[:0]
				}
				for !in.IsDelim(']') {
					var v5 int32
					if in.IsNull() {
						in.Skip()
					} else {
						v5 = int32(in.Int32())
					}
					out.SInt32 = append(out.SInt32, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SInt64":
			if in.IsNull() {
				in.Skip()
				out.SInt64 = nil
			} else {
				in.Delim('[')
				if out.SInt64 == nil {
					if !in.IsDelim(']') {
						out.SInt64 = make([]int64, 0, 8)
					} else {
						out.SInt64 = []int64{}
					}
				} else {
					out.SInt64 = (out.SInt64)[:0]
				}
				for !in.IsDelim(']') {
					var v6 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = int64(in.Int64())
					}
					out.SInt64 = append(out.SInt64, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SFloat32":
			if in.IsNull() {
				in.Skip()
				out.SFloat32 = nil
			} else {
				in.Delim('[')
				if out.SFloat32 == nil {
					if !in.IsDelim(']') {
						out.SFloat32 = make([]float32, 0, 16)
					} else {
						out.SFloat32 = []float32{}
					}
				} else {
					out.SFloat32 = (out.SFloat32)[:0]
				}
				for !in.IsDelim(']') {
					var v7 float32
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = float32(in.Float32())
					}
					out.SFloat32 = append(out.SFloat32, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SFloat64":
			if in.IsNull() {
				in.Skip()
				out.SFloat64 = nil
			} else {
				in.Delim('[')
				if out.SFloat64 == nil {
					if !in.IsDelim(']') {
						out.SFloat64 = make([]float64, 0, 8)
					} else {
						out.SFloat64 = []float64{}
					}
				} else {
					out.SFloat64 = (out.SFloat64)[:0]
				}
				for !in.IsDelim(']') {
					var v8 float64
					if in.IsNull() {
						in.Skip()
					} else {
						v8 = float64(in.Float64())
					}
					out.SFloat64 = append(out.SFloat64, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SBool":
			if in.IsNull() {
				in.Skip()
				out.SBool = nil
			} else {
				in.Delim('[')
				if out.SBool == nil {
					if !in.IsDelim(']') {
						out.SBool = make([]bool, 0, 64)
					} else {
						out.SBool = []bool{}
					}
				} else {
					out.SBool = (out.SBool)[:0]
				}
				for !in.IsDelim(']') {
					var v9 bool
					if in.IsNull() {
						in.Skip()
					} else {
						v9 = bool(in.Bool())
					}
					out.SBool = append(out.SBool, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Struct":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Struct).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson(out *jwriter.Writer, in TestingStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Int))
	}
	{
		const prefix string = ",\"Int8\":"
		out.RawString(prefix)
		out.Int8(int8(in.Int8))
	}
	{
		const prefix string = ",\"Int16\":"
		out.RawString(prefix)
		out.Int16(int16(in.Int16))
	}
	{
		const prefix string = ",\"Int32\":"
		out.RawString(prefix)
		out.Int32(int32(in.Int32))
	}
	{
		const prefix string = ",\"Int64\":"
		out.RawString(prefix)
		out.Int64(int64(in.Int64))
	}
	{
		const prefix string = ",\"String\":"
		out.RawString(prefix)
		out.String(string(in.String))
	}
	{
		const prefix string = ",\"Bool\":"
		out.RawString(prefix)
		out.Bool(bool(in.Bool))
	}
	{
		const prefix string = ",\"Duration\":"
		out.RawString(prefix)
		out.Int64(int64(in.Duration))
	}
	{
		const prefix string = ",\"SString\":"
		out.RawString(prefix)
		if in.SString == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.SString {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SInt\":"
		out.RawString(prefix)
		if in.SInt == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.SInt {
				if v12 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v13))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SInt8\":"
		out.RawString(prefix)
		if in.SInt8 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.SInt8 {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.Int8(int8(v15))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SInt16\":"
		out.RawString(prefix)
		if in.SInt16 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.SInt16 {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.Int16(int16(v17))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SInt32\":"
		out.RawString(prefix)
		if in.SInt32 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.SInt32 {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.Int32(int32(v19))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SInt64\":"
		out.RawString(prefix)
		if in.SInt64 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.SInt64 {
				if v20 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v21))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SFloat32\":"
		out.RawString(prefix)
		if in.SFloat32 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v22, v23 := range in.SFloat32 {
				if v22 > 0 {
					out.RawByte(',')
				}
				out.Float32(float32(v23))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SFloat64\":"
		out.RawString(prefix)
		if in.SFloat64 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.SFloat64 {
				if v24 > 0 {
					out.RawByte(',')
				}
				out.Float64(float64(v25))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SBool\":"
		out.RawString(prefix)
		if in.SBool == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.SBool {
				if v26 > 0 {
					out.RawByte(',')
				}
				out.Bool(bool(v27))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Struct\":"
		out.RawString(prefix)
		(in.Struct).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TestingStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TestingStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TestingStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TestingStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson(l, v)
}
func easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson1(in *jlexer.Lexer, out *BStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Image":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Image = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson1(out *jwriter.Writer, in BStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Image\":"
		out.RawString(prefix[1:])
		out.String(string(in.Image))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson1(l, v)
}
func easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson2(in *jlexer.Lexer, out *AStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Number = int64(in.Int64())
			}
		case "Height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = int64(in.Int64())
			}
		case "AnotherStruct":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.AnotherStruct).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson2(out *jwriter.Writer, in AStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Number\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Number))
	}
	{
		const prefix string = ",\"Height\":"
		out.RawString(prefix)
		out.Int64(int64(in.Height))
	}
	{
		const prefix string = ",\"AnotherStruct\":"
		out.RawString(prefix)
		(in.AnotherStruct).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84e285b8EncodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84e285b8DecodeGithubComARMSoftwareGolangUtilsUtilsSerializationJsonJsontestEasyjson2(l, v)
}
