// Code generated by "enumer -type=BackoffStrategy -text -json -yaml"; DO NOT EDIT.

package retry

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BackoffStrategyName = "NoBackoffNoBackoffButRetryAfterFixedBackoffFixedBackoffOrRetryAfterLinearBackoffExponentialBackoff"

var _BackoffStrategyIndex = [...]uint8{0, 9, 31, 43, 67, 80, 98}

const _BackoffStrategyLowerName = "nobackoffnobackoffbutretryafterfixedbackofffixedbackofforretryafterlinearbackoffexponentialbackoff"

func (i BackoffStrategy) String() string {
	if i < 0 || i >= BackoffStrategy(len(_BackoffStrategyIndex)-1) {
		return fmt.Sprintf("BackoffStrategy(%d)", i)
	}
	return _BackoffStrategyName[_BackoffStrategyIndex[i]:_BackoffStrategyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BackoffStrategyNoOp() {
	var x [1]struct{}
	_ = x[NoBackoff-(0)]
	_ = x[NoBackoffButRetryAfter-(1)]
	_ = x[FixedBackoff-(2)]
	_ = x[FixedBackoffOrRetryAfter-(3)]
	_ = x[LinearBackoff-(4)]
	_ = x[ExponentialBackoff-(5)]
}

var _BackoffStrategyValues = []BackoffStrategy{NoBackoff, NoBackoffButRetryAfter, FixedBackoff, FixedBackoffOrRetryAfter, LinearBackoff, ExponentialBackoff}

var _BackoffStrategyNameToValueMap = map[string]BackoffStrategy{
	_BackoffStrategyName[0:9]:        NoBackoff,
	_BackoffStrategyLowerName[0:9]:   NoBackoff,
	_BackoffStrategyName[9:31]:       NoBackoffButRetryAfter,
	_BackoffStrategyLowerName[9:31]:  NoBackoffButRetryAfter,
	_BackoffStrategyName[31:43]:      FixedBackoff,
	_BackoffStrategyLowerName[31:43]: FixedBackoff,
	_BackoffStrategyName[43:67]:      FixedBackoffOrRetryAfter,
	_BackoffStrategyLowerName[43:67]: FixedBackoffOrRetryAfter,
	_BackoffStrategyName[67:80]:      LinearBackoff,
	_BackoffStrategyLowerName[67:80]: LinearBackoff,
	_BackoffStrategyName[80:98]:      ExponentialBackoff,
	_BackoffStrategyLowerName[80:98]: ExponentialBackoff,
}

var _BackoffStrategyNames = []string{
	_BackoffStrategyName[0:9],
	_BackoffStrategyName[9:31],
	_BackoffStrategyName[31:43],
	_BackoffStrategyName[43:67],
	_BackoffStrategyName[67:80],
	_BackoffStrategyName[80:98],
}

// BackoffStrategyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BackoffStrategyString(s string) (BackoffStrategy, error) {
	if val, ok := _BackoffStrategyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BackoffStrategyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BackoffStrategy values", s)
}

// BackoffStrategyValues returns all values of the enum
func BackoffStrategyValues() []BackoffStrategy {
	return _BackoffStrategyValues
}

// BackoffStrategyStrings returns a slice of all String values of the enum
func BackoffStrategyStrings() []string {
	strs := make([]string, len(_BackoffStrategyNames))
	copy(strs, _BackoffStrategyNames)
	return strs
}

// IsABackoffStrategy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BackoffStrategy) IsABackoffStrategy() bool {
	for _, v := range _BackoffStrategyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BackoffStrategy
func (i BackoffStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BackoffStrategy
func (i *BackoffStrategy) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BackoffStrategy should be a string, got %s", data)
	}

	var err error
	*i, err = BackoffStrategyString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for BackoffStrategy
func (i BackoffStrategy) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for BackoffStrategy
func (i *BackoffStrategy) UnmarshalText(text []byte) error {
	var err error
	*i, err = BackoffStrategyString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for BackoffStrategy
func (i BackoffStrategy) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for BackoffStrategy
func (i *BackoffStrategy) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = BackoffStrategyString(s)
	return err
}
