// Code generated by "enumer -type=ErrorAction -text -json -yaml"; DO NOT EDIT.

package step

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ErrorActionName = "ErrorActionStopErrorActionContinueErrorActionSkipErrorActionFallback"

var _ErrorActionIndex = [...]uint8{0, 15, 34, 49, 68}

const _ErrorActionLowerName = "erroractionstoperroractioncontinueerroractionskiperroractionfallback"

func (i ErrorAction) String() string {
	if i < 0 || i >= ErrorAction(len(_ErrorActionIndex)-1) {
		return fmt.Sprintf("ErrorAction(%d)", i)
	}
	return _ErrorActionName[_ErrorActionIndex[i]:_ErrorActionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ErrorActionNoOp() {
	var x [1]struct{}
	_ = x[ErrorActionStop-(0)]
	_ = x[ErrorActionContinue-(1)]
	_ = x[ErrorActionSkip-(2)]
	_ = x[ErrorActionFallback-(3)]
}

var _ErrorActionValues = []ErrorAction{ErrorActionStop, ErrorActionContinue, ErrorActionSkip, ErrorActionFallback}

var _ErrorActionNameToValueMap = map[string]ErrorAction{
	_ErrorActionName[0:15]:       ErrorActionStop,
	_ErrorActionLowerName[0:15]:  ErrorActionStop,
	_ErrorActionName[15:34]:      ErrorActionContinue,
	_ErrorActionLowerName[15:34]: ErrorActionContinue,
	_ErrorActionName[34:49]:      ErrorActionSkip,
	_ErrorActionLowerName[34:49]: ErrorActionSkip,
	_ErrorActionName[49:68]:      ErrorActionFallback,
	_ErrorActionLowerName[49:68]: ErrorActionFallback,
}

var _ErrorActionNames = []string{
	_ErrorActionName[0:15],
	_ErrorActionName[15:34],
	_ErrorActionName[34:49],
	_ErrorActionName[49:68],
}

// ErrorActionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ErrorActionString(s string) (ErrorAction, error) {
	if val, ok := _ErrorActionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ErrorActionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ErrorAction values", s)
}

// ErrorActionValues returns all values of the enum
func ErrorActionValues() []ErrorAction {
	return _ErrorActionValues
}

// ErrorActionStrings returns a slice of all String values of the enum
func ErrorActionStrings() []string {
	strs := make([]string, len(_ErrorActionNames))
	copy(strs, _ErrorActionNames)
	return strs
}

// IsAErrorAction returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ErrorAction) IsAErrorAction() bool {
	for _, v := range _ErrorActionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ErrorAction
func (i ErrorAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ErrorAction
func (i *ErrorAction) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ErrorAction should be a string, got %s", data)
	}

	var err error
	*i, err = ErrorActionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ErrorAction
func (i ErrorAction) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ErrorAction
func (i *ErrorAction) UnmarshalText(text []byte) error {
	var err error
	*i, err = ErrorActionString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for ErrorAction
func (i ErrorAction) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for ErrorAction
func (i *ErrorAction) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ErrorActionString(s)
	return err
}
