// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ARM-software/golang-utils/utils/serialization/frontmatter (interfaces: IFrontMatterParser)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_frontmatter.go -package=mocks github.com/ARM-software/golang-utils/utils/serialization/frontmatter IFrontMatterParser
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	frontmatter "github.com/ARM-software/golang-utils/utils/serialization/frontmatter"
	gomock "go.uber.org/mock/gomock"
)

// MockIFrontMatterParser is a mock of IFrontMatterParser interface.
type MockIFrontMatterParser struct {
	ctrl     *gomock.Controller
	recorder *MockIFrontMatterParserMockRecorder
	isgomock struct{}
}

// MockIFrontMatterParserMockRecorder is the mock recorder for MockIFrontMatterParser.
type MockIFrontMatterParserMockRecorder struct {
	mock *MockIFrontMatterParser
}

// NewMockIFrontMatterParser creates a new mock instance.
func NewMockIFrontMatterParser(ctrl *gomock.Controller) *MockIFrontMatterParser {
	mock := &MockIFrontMatterParser{ctrl: ctrl}
	mock.recorder = &MockIFrontMatterParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFrontMatterParser) EXPECT() *MockIFrontMatterParserMockRecorder {
	return m.recorder
}

// Configure mocks base method.
func (m *MockIFrontMatterParser) Configure(arg0 ...frontmatter.ParserOption) frontmatter.IFrontMatterParser {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Configure", varargs...)
	ret0, _ := ret[0].(frontmatter.IFrontMatterParser)
	return ret0
}

// Configure indicates an expected call of Configure.
func (mr *MockIFrontMatterParserMockRecorder) Configure(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockIFrontMatterParser)(nil).Configure), arg0...)
}

// Extract mocks base method.
func (m *MockIFrontMatterParser) Extract(arg0 context.Context, arg1 io.Reader) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockIFrontMatterParserMockRecorder) Extract(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockIFrontMatterParser)(nil).Extract), arg0, arg1)
}

// Parse mocks base method.
func (m *MockIFrontMatterParser) Parse(arg0 context.Context, arg1 io.Reader) (io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0, arg1)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockIFrontMatterParserMockRecorder) Parse(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockIFrontMatterParser)(nil).Parse), arg0, arg1)
}
